name       : python-exceptiongroup
version    : 1.1.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/e/exceptiongroup/exceptiongroup-1.1.0.tar.gz : bcb67d800a4497e1b404c2dd44fca47d3b7a5e5433dbab67f96c1a685cdfdf23
homepage   : https://github.com/agronholm/exceptiongroup
license    : MIT
component  : programming.python
summary    : Backport of PEP 654 (exception groups)
description: |
    This is a backport of the BaseExceptionGroup and ExceptionGroup classes from Python 3.11.
builddeps  :
    - python-build
    - python-flit-scm
    - python-installer
build      : |
    %python3_setup
install    : |
    %python3_install
